USE [master]
GO
/****** Object:  Database [PrimerParcialLUG]    Script Date: 30/9/2024 14:10:06 ******/
CREATE DATABASE [PrimerParcialLUG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PrimerParcialLUG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PrimerParcialLUG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PrimerParcialLUG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PrimerParcialLUG_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PrimerParcialLUG] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PrimerParcialLUG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PrimerParcialLUG] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET ARITHABORT OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PrimerParcialLUG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PrimerParcialLUG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PrimerParcialLUG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PrimerParcialLUG] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PrimerParcialLUG] SET  MULTI_USER 
GO
ALTER DATABASE [PrimerParcialLUG] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PrimerParcialLUG] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PrimerParcialLUG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PrimerParcialLUG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PrimerParcialLUG] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PrimerParcialLUG] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PrimerParcialLUG] SET QUERY_STORE = OFF
GO
USE [PrimerParcialLUG]
GO
/****** Object:  Table [dbo].[DEPORTE]    Script Date: 30/9/2024 14:10:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPORTE](
	[ID_DEPORTE] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_DEPORTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTIDO]    Script Date: 30/9/2024 14:10:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTIDO](
	[ID_PARTIDO] [int] IDENTITY(1,1) NOT NULL,
	[ID_DEPORTE] [int] NULL,
	[EQUIPO_LOCAL] [varchar](50) NOT NULL,
	[EQUIPO_VISITANTE] [varchar](50) NOT NULL,
	[FECHA_REGISTRO] [datetime] NULL,
	[FECHA_PARTIDO] [datetime] NULL,
	[MARCADOR_LOCAL] [int] NULL,
	[MARCADOR_VISITANTE] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PARTIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TESTDB]    Script Date: 30/9/2024 14:10:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TESTDB](
	[TEST] [int] IDENTITY(1,1) NOT NULL,
	[CAMPO1] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[TEST] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[DEPORTE] ON 
GO
INSERT [dbo].[DEPORTE] ([ID_DEPORTE], [DESCRIPCION]) VALUES (1, N'Futbol')
GO
INSERT [dbo].[DEPORTE] ([ID_DEPORTE], [DESCRIPCION]) VALUES (2, N'Basquet')
GO
INSERT [dbo].[DEPORTE] ([ID_DEPORTE], [DESCRIPCION]) VALUES (3, N'Tenis')
GO
SET IDENTITY_INSERT [dbo].[DEPORTE] OFF
GO
SET IDENTITY_INSERT [dbo].[PARTIDO] ON 
GO
INSERT [dbo].[PARTIDO] ([ID_PARTIDO], [ID_DEPORTE], [EQUIPO_LOCAL], [EQUIPO_VISITANTE], [FECHA_REGISTRO], [FECHA_PARTIDO], [MARCADOR_LOCAL], [MARCADOR_VISITANTE]) VALUES (1, 1, N'BOCA', N'BARCA', CAST(N'2024-09-30T12:34:21.260' AS DateTime), CAST(N'2025-12-24T11:11:11.000' AS DateTime), 1, 1)
GO
INSERT [dbo].[PARTIDO] ([ID_PARTIDO], [ID_DEPORTE], [EQUIPO_LOCAL], [EQUIPO_VISITANTE], [FECHA_REGISTRO], [FECHA_PARTIDO], [MARCADOR_LOCAL], [MARCADOR_VISITANTE]) VALUES (3, 3, N'Rosario', N'Cordoba', CAST(N'2024-09-30T13:57:18.667' AS DateTime), CAST(N'2024-09-30T13:57:00.730' AS DateTime), 5, 6)
GO
INSERT [dbo].[PARTIDO] ([ID_PARTIDO], [ID_DEPORTE], [EQUIPO_LOCAL], [EQUIPO_VISITANTE], [FECHA_REGISTRO], [FECHA_PARTIDO], [MARCADOR_LOCAL], [MARCADOR_VISITANTE]) VALUES (4, 2, N'Catamarca', N'Cordoba', CAST(N'2024-09-30T13:58:07.473' AS DateTime), CAST(N'2024-10-01T13:57:00.730' AS DateTime), 0, 0)
GO
SET IDENTITY_INSERT [dbo].[PARTIDO] OFF
GO
SET IDENTITY_INSERT [dbo].[TESTDB] ON 
GO
INSERT [dbo].[TESTDB] ([TEST], [CAMPO1]) VALUES (1, N'Test ok')
GO
INSERT [dbo].[TESTDB] ([TEST], [CAMPO1]) VALUES (2, N'Test 2 ok')
GO
SET IDENTITY_INSERT [dbo].[TESTDB] OFF
GO
ALTER TABLE [dbo].[PARTIDO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO
ALTER TABLE [dbo].[PARTIDO]  WITH CHECK ADD FOREIGN KEY([ID_DEPORTE])
REFERENCES [dbo].[DEPORTE] ([ID_DEPORTE])
GO
USE [master]
GO
ALTER DATABASE [PrimerParcialLUG] SET  READ_WRITE 
GO
